<?php
function build_para_args()
{
    $args = "";
    if ( array_key_exists ("docid", $_GET) )
        $args .= '&docid='.$_GET["docid"];
    if ( array_key_exists ("target", $_GET) )
        $args .= '&target='.$_GET["target"];
    if ( array_key_exists ("format", $_GET) )
        $args .= '&format='.$_GET["target"];
    if ( strpos($args,'&')==0 )
        $args = substr($args,1);
    return $args;
}
function para_block_info() {
  $blocks['para'] = array(
    'info' => t('Fetch miscallaneous HTML or Markdown files'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function para_help($path, $arg) {
    switch ($path)
    {
        case "admin/help#para":
            return '<p>' .
                t("Fetch HTML or Markdown files")
                . '</p>';
            break;
    }
}
function para_block_view($delta = '') {
  switch ($delta) {
    case 'para':
      $args = build_para_args();
      $mod_path = drupal_get_path('module', 'para');
      $block['content'] = '<script type="text/javascript" src="'.$mod_path
          .'/js/para.js?'.$args.'"></script>';
      return $block;
  }
}

