<?php
function my_add_meta_tag( $name, $value, $tag )
{
    $element = array(
        '#tag' => 'meta',
        '#attributes' => array(
            'name'=> $name,
            'content' => $value
        )
    );
    drupal_add_html_head($element,$tag);
}
function timeline_preprocess_page(&$vars)
{
    if ( strpos(request_uri(),"timeline") )
    {
        my_add_meta_tag('description','Timeline','Timeline');
        drupal_add_js(drupal_get_path('module','timeline').'/js/timeline.js','file');
        drupal_add_js(drupal_get_path('module','timeline').'/js/timeline-embed.js','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/timeline.css','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/ecdosis-timeline.css','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/fonts/font.default.css?v1','external');
    }
}
function language( $param )
{
    if ( $param === "" )
        return "en";
    else
        return $param;
}
function timeline_all()
{
    $mod_path = drupal_get_path('module', 'timeline');
    $html = '<div id="timeline-embed"></div>'
	.'<script type="text/javascript" src="'.$mod_path
        .'/js/ecdosis-timeline.js?target=timeline-embed&'
        .'docid='.$_GET['docid']
        .'&modpath='.$mod_path
        .'&title='.$_GET['title']
        .'&subtitle='.$_GET['subtitle']
        .'&event_type='.$_GET['event_type']
        .'&language='.language($_GET['language'])
        .'"></script>';
    return $html;
}
function timeline_menu()
{
    $items = array();
    $items['admin/config/content/timeline'] = array(
        'title'=>'Timeline',
        'description' => 'Events in the life of an author',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('timeline_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM
    );
    $items['timeline'] = array(
        'title' => 'timeline',
        'page callback' => 'timeline_all',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}
function timeline_block_info() {
  $blocks['timeline'] = array(
    'info' => t('Timeline'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function timeline_help($path, $arg) {
    switch ($path)
    {
        case "admin/help#timeline":
            return '<p>' .
                t("Events in the life of an author/production of a work.")
                . '</p>';
            break;
    }
}
function timeline_block_view($delta = '') {
  switch ($delta) {
    case 'timeline':
      $block['subject'] = t('Timeline');
      $block['content'] = '';
      return $block;
  }
}
/**
 * Page callback: Events settings
 * @param form the form object to override
 * @param form_state the current state of the form (keys->values)
 * @return an updated form
 * @see events_menu()
 */
function timeline_form($form, &$form_state)
{
    $form['timeline_docid'] = array(
        '#type' => 'textfield',
        '#title' => t('Default docid'),
        '#default_value' => 'italian/deroberto',
        '#size' => 128,
        '#maxlength' => 256,
        '#required' => TRUE
    );
    return $form;
}

