<?php
function my_add_meta_tag( $name, $value, $tag )
{
    $element = array(
        '#tag' => 'meta',
        '#attributes' => array(
            'name'=> $name,
            'content' => $value
        )
    );
    drupal_add_html_head($element,$tag);
}
function timeline_preprocess_page(&$vars)
{
    if ( strpos(request_uri(),"timeline")||strpos(request_uri(),"biography") )
    {
        my_add_meta_tag('description','Timeline','Timeline');
        drupal_add_js(drupal_get_path('module','timeline').'/js/timeline.js','file');
        drupal_add_js(drupal_get_path('module','timeline').'/js/timeline-embed.js','file');
        drupal_add_js(drupal_get_path('module','timeline').'/js/ecdosis-timeline.js','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/timeline.css','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/ecdosis-timeline.css','file');
        drupal_add_css(drupal_get_path('module','timeline').'/css/fonts/font.default.css?v1','external');
    }
}
function timeline_block_info() {
  $blocks['timeline'] = array(
    'info' => t('Timeline'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function timeline_help($path, $arg) {
    switch ($path)
    {
        case "admin/help#timeline":
            return '<p>' .
                t("Events in the life of an author/production of a work.")
                . '</p>';
            break;
    }
}

