<?php
function gridhome_preprocess_page(&$vars)
{
    if ( strpos(request_uri(),"gridhome")||drupal_is_front_page() )
    {
        drupal_add_css(drupal_get_path('module','gridhome').'/gridhome.css','file');
    }
}
function gridhome_block_info() {
  $blocks['gridhome'] = array(
    'info' => t('Display a homepage in a grid'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
function gridhome_help($path, $arg) {
switch ($path) 
  {
    case "admin/help#gridhome":
      return '<p>' . t("Displays an interactive home page") . '</p>';
      break;
  }
}
function gridhome_block_view($delta = '') {
  switch ($delta) {
    case 'gridhome':
      $mod_path = drupal_get_path('module', 'gridhome');
      $block['content'] = '<script type="text/javascript" src="'
          .$mod_path.'/gridhome.js?target=content&modpath='.$mod_path.
          '&docid=english/harpur/home"></script>';
      return $block;
  }
}

