<?php
function browse_preprocess_page(&$vars)
{
    if ( strpos(request_uri(),"browse") )
    {
        drupal_add_js(drupal_get_path('module', 'browse').'/js/browse.js','file');
        drupal_add_css(drupal_get_path('module','browse').'/css/browse.css','file');
    }
}
function browse_help($path, $arg) 
{
    switch ($path) 
    {
        case "admin/help#browse":
            return '<p>' . 
                t("Displays a set of browsable index.") 
                . '</p>';
            break;
  }
}
/**
 * Implements hook_block_info().
 */
function browse_block_info() 
{
    $blocks['browse'] = array(
        'info' => t('Browsable list'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}
